services:
  zookeeper:
    image: bitnamilegacy/zookeeper:3.9.3-debian-12-r22
    ports:
      - "8798:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - dudes_network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  kafka:
    image: bitnamilegacy/kafka:3.9.0-debian-12-r9
    ports:
      - "9097:9092"
      - "29092:29092"
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - dudes_network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT_HOST://kafka:9092,PLAINTEXT://127.0.0.1:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - sh
        - -c
        - /opt/bitnami/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:29092
      interval: 30s
      timeout: 10s
      retries: 5
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "9089:8080"
    networks:
      - dudes_network
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    restart: none

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  dudes_network:
    name: local-dudes-network
